package shared;

public enum ResponseTypes {

    CONNECTION_ESTABLISHED,

    CATEGORY_REQUEST_ACCEPTED,
    CATEGORY_REQUEST_REJECTED,
    CATEGORY_REQUEST_UPDATE,

    SUBSCRIPTION_ACCEPTED,
    SUBSCRIPTION_REJECTED,

    PRODUCTS_REQUEST,
    CONTACT_REQUEST,
    UNKNOWN_REQUEST

}
